# Copyright (c) 2020 UAVCAN Consortium
# This software is distributed under the terms of the MIT License.
# Author: Pavel Kirienko <pavel@uavcan.org>

import os
import shutil
from pathlib import Path
import nox


@nox.session(python=False)
def clean(session):
    wildcards = [
        "static",
        "uploads",
        "htmlcov",
        ".coverage*",
        ".*cache",
        ".*compiled",
        "*.egg-info",
        "*.log",
        "*.tmp",
        ".nox",
    ]
    for w in wildcards:
        for f in Path.cwd().glob(w):
            session.log(f"Removing: {f}")
            shutil.rmtree(f, ignore_errors=True)


# @nox.session(python=["3.8", "3.9"], reuse_venv=True)
# def test(session):
#     # Spin up the backend setup.
#     # This is needed both to run full integration tests and to
#     # do a sanity check on whether the server starts properly.
#     session.install("-r", "requirements.txt")
#     session.run_always("python3", "-m", "nunaserver", "&")
#     session.run_always("celery",
#                        "-A",
#                        "nunaserver.generator",
#                        "worker", "--loglevel=info", "&")
#     session.run_always("python3", "-m", "http.server", "&")
#     session.run_always("docker", "run", "redis", "&")
#
#     # MyPy has to be run in the same session because:
#     #   1. It requires access to the code generated by the test suite.
#     #   2. It has to be run separately per Python version we support.
#     # If the interpreter is not CPython, this may need to be conditionally disabled.
#     session.install("mypy == 0.790")
#     session.run("mypy", "--strict", *map(str, src_dirs))


@nox.session(reuse_venv=True)
def lint(session):
    session.install("-r", "requirements.txt")
    session.install("-r", "requirements-dev.txt")

    session.install("pylint == 2.6.0")
    session.run("pylint", "nunaserver", success_codes=[2, 4, 8, 16, 28, 32])

    session.install("black == 20.8b1")
    session.run("black", "--check", ".")
