# --------------------------------------------------  BLACK  --------------------------------------------------
[tool.black]
line-length = 120
target-version = ['py311']
include = '''
(src/.*\.pyi?$)
|
(noxfile.py$)
'''