version: "3"
services:
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nunaserver/static:/var/www/static/api/static
    ports:
      - "8000:80"
  celery:
    image: nunaweb-python:latest
    build:
      context: ..
      dockerfile: deployment/Dockerfile.server
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - NS_MINIO_URL=minio:9000
      - NS_MINIO_RESULTS=http://localhost:8000/api/storage/results # Change
      - NS_MINIO_ACCESS_KEY=nunaweb
      - NS_MINIO_SECRET_KEY=supersecurepassword
      - NS_REDIS_RESULT=redis://redis
      - NS_REDIS_BROKER=redis://redis:6379/0
      - NS_LOG_LEVEL=40
    command: "celery -A nunaserver.generator worker --loglevel=info"
  nunaserver:
    image: nunaweb-python:latest
    build:
      context: ..
      dockerfile: deployment/Dockerfile.server
    environment:
      - NS_UPLOAD_FOLDER=/nunaserver/uploads
      - NS_REDIS_RESULT=redis://redis
      - NS_REDIS_BROKER=redis://redis:6379/0
      - NS_MINIO_URL=minio:9000
      - NS_MINIO_RESULTS=http://localhost:8000/api/storage/results # Change
      - NS_MINIO_ACCESS_KEY=nunaweb
      - NS_MINIO_SECRET_KEY=supersecurepassword
      - NS_LOG_LEVEL=40
    command: "gunicorn -w 4 -b 0.0.0.0:8000 nunaserver.wsgi:app"
  minio:
    image: minio/minio:latest
    volumes:
      - ./data:/data
    environment:
      # CHANGE THIS
      MINIO_ROOT_USER: nunaweb
      MINIO_ROOT_PASSWORD: supersecurepassword
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  redis:
    image: redis:latest
