name: Production Deployment

on:
  push:
    branches:
      - maintenance

jobs:
  nunaweb-proxy:
    name: Build nunaweb-proxy image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


  nunaweb-server:
    name: Build nunaweb-server image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


  nunaweb-web:
    name: Build nunaweb-web image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3